# Generated by Django 3.0.4 on 2020-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=200)),
                ('chinese_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('date_purchased', models.DateTimeField(verbose_name='date purchased')),
                ('full_sun', models.BinaryField(default=0)),
                ('half_sun', models.BinaryField(default=1)),
                ('shadow', models.BinaryField(default=0)),
                ('min_temp', models.IntegerField(default=15)),
                ('max_temp', models.IntegerField(default=42)),
                ('comfortable_temp', models.IntegerField(default=25)),
                ('family', models.CharField(max_length=200)),
            ],
        ),
    ]
