# Generated by Django 3.0.4 on 2020-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='comments',
            field=models.CharField(default='noname', max_length=1000),
            preserve_default=False,
        ),
    ]
