# Generated by Django 3.0.4 on 2020-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplants', '0003_auto_20200725_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='full_sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.TextField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
