# Generated by Django 3.0.4 on 2020-07-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseplants', '0004_auto_20200725_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='full_sun',
        ),
    ]
